### ISSUE TITLE
Support for line breaks?

### ISSUE THREAD

**Issue by jpblair** [arnabk/java-dogstatsd-client#1]
I'm trying to post events whose text contains line breaks.  Yet when they show up in Datadog, only the first line is shown.  Perhaps it's a UDP issue?  The DogStatsD documentation indicates that line breaks are supported:

http://docs.datadoghq.com/guides/dogstatsd/

Thanks for your help.

**Comment by arnabk** [comment]
Have you tried passing '\n'?

**Comment by jpblair** [comment]
After setting up a UDP listener, it appears that your library passes through \n as expected.  Looks like it could be an upstream Datadog Agent issue - currently talking to their support team to figure out if some special escaping is required.

**Comment by arnabk** [comment]
Well logically, you should be sending \n or \r in a new line because everything should be passed as a single line to the Datadog server. 

I am closing this defect for now since its not an issue with the library.

**Comment by jpblair** [comment]
After an email thread with someone from Datadog's support team, it appears that \\n needs to be sent instead of \n.  Not really sure why this is.

**Comment by jpblair** [comment]
Confirming that by manually doing a String.replace("\n","\\n") the line breaks come through as expected.  Not sure if the same issue would occur on all platforms, but having this replacement occur automatically in the library could be useful.

**Comment by arnabk** [comment]
I am not sure if I understand your point correctly. What are we replacing? String.replace("\n","\n") - Replace \n with \n?

**Comment by jpblair** [comment]
I just noticed that Github's editor escaped my \\n with two slashes to \n with one.  I'll edit to reflect what it should be.

**Comment by jpblair** [comment]
Sorry about the confusion there.
