### ISSUE TITLE
Rename com.timgroup package

### ISSUE THREAD

**Issue by scravy** [arnabk/java-dogstatsd-client#2]
This library is effectively repackaging the library it was forked from. This causes classpath loading issues.

If you have a library that depends on the forked library and another one which depends on this, you end up with two classes with the same name with possibly different binary interfaces (e.g. in the `count` method on `NonBlockingStatsDClient`).

Please never ever do something foolish as this. Just properly rename that package.

This can be the case with: Transitive dependencies. If A depends on B which depends on the original statsd and A depends on C which depends on dogstatsd you end up having two dependencies on your classpath exporting the same package.

I also opened an issue on the repo which this is a fork from: https://github.com/indeedeng/java-dogstatsd-client/issues/28

**Comment by arnabk** [comment]
By renaming the package that you inherited from upstream, you kill the entire github forking modeling. If you do that, you would never be able to merge code from upstream to your fork. You should never do that unless you are sure that you would never update your fork with the upstream. 

If you would never update your code with upstream, then why to fork at all?

If your project is dependent on two different forks which inherited from same upstream, then your project requirements are in a state wherein you need features from both the forks. In that case, you should create your own project and copy the bits and pieces from each project.
