### ISSUE TITLE
Add support for sending sample_rate while submitting metrics

### ISSUE THREAD

**Issue by debraj-manna** [arnabk/java-dogstatsd-client#3]
Add support for sending [sample_rate](http://docs.datadoghq.com/guides/dogstatsd/#sample-rates) while submitting metrics to datadog.

**Comment by arnabk** [comment]
@debraj-manna Feel free to submit PR

**Comment by debraj-manna** [comment]
@arnabk - Submitted a PR.

**Comment by arnabk** [comment]
Merged
