### ISSUE TITLE
PR build in travis CI is failing

### ISSUE THREAD

**Issue by debraj-manna** [arnabk/java-dogstatsd-client#8]
The PR build in [travis-ci](https://travis-ci.org/arnabk/java-dogstatsd-client/builds/152728919) is failing.

**Comment by arnabk** [comment]
Check the last build status

**Comment by debraj-manna** [comment]
@arnabk  - I meant the PR build. I raised a test [PR](https://github.com/arnabk/java-dogstatsd-client/pull/9) . 

The travis is reporting failure:-

https://travis-ci.org/arnabk/java-dogstatsd-client/builds/157697073

**Comment by debraj-manna** [comment]
I am not able to reopen this one.
